name: Auto commit

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 7,9,11 * * 1,3"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Modify last update
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > LAST_UPDATED

      - name: Commit and Push
        run: |
          git config user.name "prusrafal"
          git config user.email "prus.rafal@icloud.com"

          git add LAST_UPDATED

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          EMOJIS=("😂" "😱" "👿" "💩" "🙏" "🙈" "🐐" "🤖" "🟩" "👻")
          RAND=$((RANDOM % ${#EMOJIS[@]}))

          git commit -m "chore(bot): ${EMOJIS[$RAND]} auto commit"
          git push
